Add support for typescript in the CheckJS mode
In the checkJs mode, typescript will also check your JavaScript files using the types inside the JsDoc comments.

At the moment, you cannot pass a .js files to tsc-files, because it gives the following error:

    error TS5042: Option 'project' cannot be mixed with source files on a command line.

This is because the js files are appended after the tsc command. This commit allows the tsc-files plugin to also work with the checkJs mode